plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  DisplayCopNames: true
  Include:
    - 'Rakefile'
    - '**/*.rb'
    - '**/*.rake'
    - 'Gemfile'
  Exclude:
    - 'bin/**/*'
  NewCops: enable

Lint/EmptyBlock:
  Exclude:
    - 'config/routes.rb'

RSpec/MultipleExpectations:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'spec/dummy/Rakefile'
